### PR TITLE
Update timestamp conversion in client

### PR DESCRIPTION
**Pull request by markovamaria**
Reverting of str converting for timestamp to avoid error 'str object has no attribute timestamp'

Resolves: #209

### CODE REVIEW

**Comment by markovamaria** [comment]
Hi @filipecosta90 , @slice4e , could you please review?

**Comment by filipecosta90** [comment]
> Hi @filipecosta90 , @slice4e , could you please review?

@markovamaria please include a unit test that confirms we're OK with this change.

**Review by filipecosta90 — CHANGES_REQUESTED** [review]
requires test. I can add it if required.

**Comment by markovamaria** [comment]
> requires test. I can add it if required.

added

**Comment by markovamaria** [comment]
REF 1: before fix:
image

REF 2:  after test added, before fix added: 
image

EXP: after test and fix added:
image

**Comment by markovamaria** [comment]
@filipecosta90 , please take a look. I've added test and related screenshots.

**Review by slice4e — APPROVED** [review]

**Review by filipecosta90 — APPROVED** [review]

**Comment by filipecosta90** [comment]
Nice. Thank you @markovamaria !

**Pull request merged**
