### PR TITLE
added support for bitfield command.

### PR DESCRIPTION
**Pull request by slice4e**
added support for bitfield command.

### CODE REVIEW

**Review by filipecosta90 — APPROVED** [review]

**Comment by filipecosta90** [comment]
```
 2022-12-15 20:20:27 WARNING there is a difference between specified test-commands in the yaml (name=memtier_benchmark-1key-100MB-string-bitfield) and the ones we've detected ['get']!=['get', 'bitfield']
2022-12-15 20:20:27 WARNING there is a difference between specified test-groups in the yaml (name=memtier_benchmark-1key-100MB-string-bitfield) and the ones we've detected ['string']!=['bitmap']
```
@slice4e please correct the groups of test :)

**Review by filipecosta90 — CHANGES_REQUESTED** [review]
2022-12-15 20:20:27 WARNING there is a difference between specified test-commands in the yaml (name=memtier_benchmark-1key-100MB-string-bitfield) and the ones we've detected ['get']!=['get', 'bitfield']
2022-12-15 20:20:27 WARNING there is a difference between specified test-groups in the yaml (name=memtier_benchmark-1key-100MB-string-bitfield) and the ones we've detected ['string']!=['bitmap']

**Review by filipecosta90 — APPROVED** [review]

**Comment by slice4e** [comment]
I believe I fixed it. and pushed a new commit

**Comment by filipecosta90** [comment]
> I believe I fixed it. and pushed a new commit

Confirmed fixed in https://github.com/redis/redis-benchmarks-specification/actions/runs/3707733491/jobs/6284499636 
Merging. Thank you @slice4e !

**Pull request merged**
